package test.dao;

import java.util.List;
import test.model.Association1;

public interface Association1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String ordorderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int insert(Association1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    Association1 selectByPrimaryKey(String ordorderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    List<Association1> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Association1 record);
}