package test.dao;

import java.util.List;
import test.model.CityArea;

public interface CityAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_area
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_area
     *
     * @mbg.generated
     */
    int insert(CityArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_area
     *
     * @mbg.generated
     */
    CityArea selectByPrimaryKey(String areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_area
     *
     * @mbg.generated
     */
    List<CityArea> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_area
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CityArea record);
}