package test.dao;

import java.util.List;
import test.model.DeleveryRange;

public interface DeleveryRangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delevery_range
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String ranqelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delevery_range
     *
     * @mbg.generated
     */
    int insert(DeleveryRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delevery_range
     *
     * @mbg.generated
     */
    DeleveryRange selectByPrimaryKey(String ranqelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delevery_range
     *
     * @mbg.generated
     */
    List<DeleveryRange> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delevery_range
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeleveryRange record);
}