package test.dao;

import java.util.List;
import test.model.DeliveryPlace;

public interface DeliveryPlaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_place
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_place
     *
     * @mbg.generated
     */
    int insert(DeliveryPlace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_place
     *
     * @mbg.generated
     */
    DeliveryPlace selectByPrimaryKey(String depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_place
     *
     * @mbg.generated
     */
    List<DeliveryPlace> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_place
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeliveryPlace record);
}