package test.dao;

import java.util.List;
import test.model.DeliveryReceipt;

public interface DeliveryReceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_receipt
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deliveryreceiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_receipt
     *
     * @mbg.generated
     */
    int insert(DeliveryReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_receipt
     *
     * @mbg.generated
     */
    DeliveryReceipt selectByPrimaryKey(String deliveryreceiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_receipt
     *
     * @mbg.generated
     */
    List<DeliveryReceipt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_receipt
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeliveryReceipt record);
}