package test.dao;

import java.util.List;
import test.model.Privance;

public interface PrivanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privance
     *
     * @mbg.generated
     */
    int insert(Privance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privance
     *
     * @mbg.generated
     */
    Privance selectByPrimaryKey(String provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privance
     *
     * @mbg.generated
     */
    List<Privance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Privance record);
}