package test.model;

import java.util.Date;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_ID
     *
     * @mbg.generated
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.ropute_ID
     *
     * @mbg.generated
     */
    private String roputeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_Type
     *
     * @mbg.generated
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_Orgin
     *
     * @mbg.generated
     */
    private String carOrgin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_ProDate
     *
     * @mbg.generated
     */
    private Date carProdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_BuyDate
     *
     * @mbg.generated
     */
    private Date carBuydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_capaCity
     *
     * @mbg.generated
     */
    private Integer carCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_State
     *
     * @mbg.generated
     */
    private Boolean carState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.Comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_ID
     *
     * @return the value of car.car_ID
     *
     * @mbg.generated
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_ID
     *
     * @param carId the value for car.car_ID
     *
     * @mbg.generated
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.ropute_ID
     *
     * @return the value of car.ropute_ID
     *
     * @mbg.generated
     */
    public String getRoputeId() {
        return roputeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.ropute_ID
     *
     * @param roputeId the value for car.ropute_ID
     *
     * @mbg.generated
     */
    public void setRoputeId(String roputeId) {
        this.roputeId = roputeId == null ? null : roputeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_Type
     *
     * @return the value of car.car_Type
     *
     * @mbg.generated
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_Type
     *
     * @param carType the value for car.car_Type
     *
     * @mbg.generated
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_Orgin
     *
     * @return the value of car.car_Orgin
     *
     * @mbg.generated
     */
    public String getCarOrgin() {
        return carOrgin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_Orgin
     *
     * @param carOrgin the value for car.car_Orgin
     *
     * @mbg.generated
     */
    public void setCarOrgin(String carOrgin) {
        this.carOrgin = carOrgin == null ? null : carOrgin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_ProDate
     *
     * @return the value of car.car_ProDate
     *
     * @mbg.generated
     */
    public Date getCarProdate() {
        return carProdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_ProDate
     *
     * @param carProdate the value for car.car_ProDate
     *
     * @mbg.generated
     */
    public void setCarProdate(Date carProdate) {
        this.carProdate = carProdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_BuyDate
     *
     * @return the value of car.car_BuyDate
     *
     * @mbg.generated
     */
    public Date getCarBuydate() {
        return carBuydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_BuyDate
     *
     * @param carBuydate the value for car.car_BuyDate
     *
     * @mbg.generated
     */
    public void setCarBuydate(Date carBuydate) {
        this.carBuydate = carBuydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_capaCity
     *
     * @return the value of car.car_capaCity
     *
     * @mbg.generated
     */
    public Integer getCarCapacity() {
        return carCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_capaCity
     *
     * @param carCapacity the value for car.car_capaCity
     *
     * @mbg.generated
     */
    public void setCarCapacity(Integer carCapacity) {
        this.carCapacity = carCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_State
     *
     * @return the value of car.car_State
     *
     * @mbg.generated
     */
    public Boolean getCarState() {
        return carState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_State
     *
     * @param carState the value for car.car_State
     *
     * @mbg.generated
     */
    public void setCarState(Boolean carState) {
        this.carState = carState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.Comments
     *
     * @return the value of car.Comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.Comments
     *
     * @param comments the value for car.Comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}