package test.model;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.Cu_ID
     *
     * @mbg.generated
     */
    private String cuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_Name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_Psd
     *
     * @mbg.generated
     */
    private String customerPsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_sex
     *
     * @mbg.generated
     */
    private String customerSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.Brithday
     *
     * @mbg.generated
     */
    private Date brithday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.Comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.Cu_ID
     *
     * @return the value of customer.Cu_ID
     *
     * @mbg.generated
     */
    public String getCuId() {
        return cuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.Cu_ID
     *
     * @param cuId the value for customer.Cu_ID
     *
     * @mbg.generated
     */
    public void setCuId(String cuId) {
        this.cuId = cuId == null ? null : cuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_Name
     *
     * @return the value of customer.customer_Name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_Name
     *
     * @param customerName the value for customer.customer_Name
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_Psd
     *
     * @return the value of customer.customer_Psd
     *
     * @mbg.generated
     */
    public String getCustomerPsd() {
        return customerPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_Psd
     *
     * @param customerPsd the value for customer.customer_Psd
     *
     * @mbg.generated
     */
    public void setCustomerPsd(String customerPsd) {
        this.customerPsd = customerPsd == null ? null : customerPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_sex
     *
     * @return the value of customer.customer_sex
     *
     * @mbg.generated
     */
    public String getCustomerSex() {
        return customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_sex
     *
     * @param customerSex the value for customer.customer_sex
     *
     * @mbg.generated
     */
    public void setCustomerSex(String customerSex) {
        this.customerSex = customerSex == null ? null : customerSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.Brithday
     *
     * @return the value of customer.Brithday
     *
     * @mbg.generated
     */
    public Date getBrithday() {
        return brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.Brithday
     *
     * @param brithday the value for customer.Brithday
     *
     * @mbg.generated
     */
    public void setBrithday(Date brithday) {
        this.brithday = brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.tel
     *
     * @return the value of customer.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.tel
     *
     * @param tel the value for customer.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.Comments
     *
     * @return the value of customer.Comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.Comments
     *
     * @param comments the value for customer.Comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}