package test.model;

public class DeleveryRange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delevery_range.ranqel_ID
     *
     * @mbg.generated
     */
    private String ranqelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delevery_range.dep_ID
     *
     * @mbg.generated
     */
    private String depId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delevery_range.area_ID
     *
     * @mbg.generated
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delevery_range.ranqel_Name
     *
     * @mbg.generated
     */
    private String ranqelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delevery_range.delivery_price
     *
     * @mbg.generated
     */
    private String deliveryPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delevery_range.Comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delevery_range.ranqel_ID
     *
     * @return the value of delevery_range.ranqel_ID
     *
     * @mbg.generated
     */
    public String getRanqelId() {
        return ranqelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delevery_range.ranqel_ID
     *
     * @param ranqelId the value for delevery_range.ranqel_ID
     *
     * @mbg.generated
     */
    public void setRanqelId(String ranqelId) {
        this.ranqelId = ranqelId == null ? null : ranqelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delevery_range.dep_ID
     *
     * @return the value of delevery_range.dep_ID
     *
     * @mbg.generated
     */
    public String getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delevery_range.dep_ID
     *
     * @param depId the value for delevery_range.dep_ID
     *
     * @mbg.generated
     */
    public void setDepId(String depId) {
        this.depId = depId == null ? null : depId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delevery_range.area_ID
     *
     * @return the value of delevery_range.area_ID
     *
     * @mbg.generated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delevery_range.area_ID
     *
     * @param areaId the value for delevery_range.area_ID
     *
     * @mbg.generated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delevery_range.ranqel_Name
     *
     * @return the value of delevery_range.ranqel_Name
     *
     * @mbg.generated
     */
    public String getRanqelName() {
        return ranqelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delevery_range.ranqel_Name
     *
     * @param ranqelName the value for delevery_range.ranqel_Name
     *
     * @mbg.generated
     */
    public void setRanqelName(String ranqelName) {
        this.ranqelName = ranqelName == null ? null : ranqelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delevery_range.delivery_price
     *
     * @return the value of delevery_range.delivery_price
     *
     * @mbg.generated
     */
    public String getDeliveryPrice() {
        return deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delevery_range.delivery_price
     *
     * @param deliveryPrice the value for delevery_range.delivery_price
     *
     * @mbg.generated
     */
    public void setDeliveryPrice(String deliveryPrice) {
        this.deliveryPrice = deliveryPrice == null ? null : deliveryPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delevery_range.Comments
     *
     * @return the value of delevery_range.Comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delevery_range.Comments
     *
     * @param comments the value for delevery_range.Comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}