package test.model;

public class DeliveryPlace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_place.dep_ID
     *
     * @mbg.generated
     */
    private String depId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_place.mg_ID
     *
     * @mbg.generated
     */
    private String mgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_place.dep_Name
     *
     * @mbg.generated
     */
    private String depName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_place.province_Name
     *
     * @mbg.generated
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_place.city_Name
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_place.mg_Name
     *
     * @mbg.generated
     */
    private String mgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_place.dep_Tel
     *
     * @mbg.generated
     */
    private String depTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_place.dep_Addr
     *
     * @mbg.generated
     */
    private String depAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_place.Comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_place.dep_ID
     *
     * @return the value of delivery_place.dep_ID
     *
     * @mbg.generated
     */
    public String getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_place.dep_ID
     *
     * @param depId the value for delivery_place.dep_ID
     *
     * @mbg.generated
     */
    public void setDepId(String depId) {
        this.depId = depId == null ? null : depId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_place.mg_ID
     *
     * @return the value of delivery_place.mg_ID
     *
     * @mbg.generated
     */
    public String getMgId() {
        return mgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_place.mg_ID
     *
     * @param mgId the value for delivery_place.mg_ID
     *
     * @mbg.generated
     */
    public void setMgId(String mgId) {
        this.mgId = mgId == null ? null : mgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_place.dep_Name
     *
     * @return the value of delivery_place.dep_Name
     *
     * @mbg.generated
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_place.dep_Name
     *
     * @param depName the value for delivery_place.dep_Name
     *
     * @mbg.generated
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_place.province_Name
     *
     * @return the value of delivery_place.province_Name
     *
     * @mbg.generated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_place.province_Name
     *
     * @param provinceName the value for delivery_place.province_Name
     *
     * @mbg.generated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_place.city_Name
     *
     * @return the value of delivery_place.city_Name
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_place.city_Name
     *
     * @param cityName the value for delivery_place.city_Name
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_place.mg_Name
     *
     * @return the value of delivery_place.mg_Name
     *
     * @mbg.generated
     */
    public String getMgName() {
        return mgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_place.mg_Name
     *
     * @param mgName the value for delivery_place.mg_Name
     *
     * @mbg.generated
     */
    public void setMgName(String mgName) {
        this.mgName = mgName == null ? null : mgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_place.dep_Tel
     *
     * @return the value of delivery_place.dep_Tel
     *
     * @mbg.generated
     */
    public String getDepTel() {
        return depTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_place.dep_Tel
     *
     * @param depTel the value for delivery_place.dep_Tel
     *
     * @mbg.generated
     */
    public void setDepTel(String depTel) {
        this.depTel = depTel == null ? null : depTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_place.dep_Addr
     *
     * @return the value of delivery_place.dep_Addr
     *
     * @mbg.generated
     */
    public String getDepAddr() {
        return depAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_place.dep_Addr
     *
     * @param depAddr the value for delivery_place.dep_Addr
     *
     * @mbg.generated
     */
    public void setDepAddr(String depAddr) {
        this.depAddr = depAddr == null ? null : depAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_place.Comments
     *
     * @return the value of delivery_place.Comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_place.Comments
     *
     * @param comments the value for delivery_place.Comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}