package test.model;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mql_ID
     *
     * @mbg.generated
     */
    private String mqlId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.role_ID
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_Name
     *
     * @mbg.generated
     */
    private String managerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_Psd
     *
     * @mbg.generated
     */
    private String managerPsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_Sex
     *
     * @mbg.generated
     */
    private String managerSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.Tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.Address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.Comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mql_ID
     *
     * @return the value of manager.mql_ID
     *
     * @mbg.generated
     */
    public String getMqlId() {
        return mqlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mql_ID
     *
     * @param mqlId the value for manager.mql_ID
     *
     * @mbg.generated
     */
    public void setMqlId(String mqlId) {
        this.mqlId = mqlId == null ? null : mqlId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.role_ID
     *
     * @return the value of manager.role_ID
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.role_ID
     *
     * @param roleId the value for manager.role_ID
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_Name
     *
     * @return the value of manager.manager_Name
     *
     * @mbg.generated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_Name
     *
     * @param managerName the value for manager.manager_Name
     *
     * @mbg.generated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_Psd
     *
     * @return the value of manager.manager_Psd
     *
     * @mbg.generated
     */
    public String getManagerPsd() {
        return managerPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_Psd
     *
     * @param managerPsd the value for manager.manager_Psd
     *
     * @mbg.generated
     */
    public void setManagerPsd(String managerPsd) {
        this.managerPsd = managerPsd == null ? null : managerPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_Sex
     *
     * @return the value of manager.manager_Sex
     *
     * @mbg.generated
     */
    public String getManagerSex() {
        return managerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_Sex
     *
     * @param managerSex the value for manager.manager_Sex
     *
     * @mbg.generated
     */
    public void setManagerSex(String managerSex) {
        this.managerSex = managerSex == null ? null : managerSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.Tel
     *
     * @return the value of manager.Tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.Tel
     *
     * @param tel the value for manager.Tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.Address
     *
     * @return the value of manager.Address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.Address
     *
     * @param address the value for manager.Address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.Comments
     *
     * @return the value of manager.Comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.Comments
     *
     * @param comments the value for manager.Comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}