package test.model;

import java.math.BigDecimal;

public class Order1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.order_ID
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.Car_ID
     *
     * @mbg.generated
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.cu_ID
     *
     * @mbg.generated
     */
    private String cuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.post_Pname
     *
     * @mbg.generated
     */
    private String postPname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.post_PTel
     *
     * @mbg.generated
     */
    private String postPtel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.post_Paddr
     *
     * @mbg.generated
     */
    private String postPaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.get_Pname
     *
     * @mbg.generated
     */
    private String getPname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.get_Ptel
     *
     * @mbg.generated
     */
    private String getPtel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.get_Addr
     *
     * @mbg.generated
     */
    private String getAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.goods_Name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.goods_Weight
     *
     * @mbg.generated
     */
    private Integer goodsWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.order_Type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.order_State
     *
     * @mbg.generated
     */
    private String orderState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.order_PortPrice
     *
     * @mbg.generated
     */
    private BigDecimal orderPortprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.transpor_Price
     *
     * @mbg.generated
     */
    private BigDecimal transporPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.delivery_Price
     *
     * @mbg.generated
     */
    private BigDecimal deliveryPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.total_price
     *
     * @mbg.generated
     */
    private String totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order1.Comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.order_ID
     *
     * @return the value of order1.order_ID
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.order_ID
     *
     * @param orderId the value for order1.order_ID
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.Car_ID
     *
     * @return the value of order1.Car_ID
     *
     * @mbg.generated
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.Car_ID
     *
     * @param carId the value for order1.Car_ID
     *
     * @mbg.generated
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.cu_ID
     *
     * @return the value of order1.cu_ID
     *
     * @mbg.generated
     */
    public String getCuId() {
        return cuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.cu_ID
     *
     * @param cuId the value for order1.cu_ID
     *
     * @mbg.generated
     */
    public void setCuId(String cuId) {
        this.cuId = cuId == null ? null : cuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.post_Pname
     *
     * @return the value of order1.post_Pname
     *
     * @mbg.generated
     */
    public String getPostPname() {
        return postPname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.post_Pname
     *
     * @param postPname the value for order1.post_Pname
     *
     * @mbg.generated
     */
    public void setPostPname(String postPname) {
        this.postPname = postPname == null ? null : postPname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.post_PTel
     *
     * @return the value of order1.post_PTel
     *
     * @mbg.generated
     */
    public String getPostPtel() {
        return postPtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.post_PTel
     *
     * @param postPtel the value for order1.post_PTel
     *
     * @mbg.generated
     */
    public void setPostPtel(String postPtel) {
        this.postPtel = postPtel == null ? null : postPtel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.post_Paddr
     *
     * @return the value of order1.post_Paddr
     *
     * @mbg.generated
     */
    public String getPostPaddr() {
        return postPaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.post_Paddr
     *
     * @param postPaddr the value for order1.post_Paddr
     *
     * @mbg.generated
     */
    public void setPostPaddr(String postPaddr) {
        this.postPaddr = postPaddr == null ? null : postPaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.get_Pname
     *
     * @return the value of order1.get_Pname
     *
     * @mbg.generated
     */
    public String getGetPname() {
        return getPname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.get_Pname
     *
     * @param getPname the value for order1.get_Pname
     *
     * @mbg.generated
     */
    public void setGetPname(String getPname) {
        this.getPname = getPname == null ? null : getPname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.get_Ptel
     *
     * @return the value of order1.get_Ptel
     *
     * @mbg.generated
     */
    public String getGetPtel() {
        return getPtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.get_Ptel
     *
     * @param getPtel the value for order1.get_Ptel
     *
     * @mbg.generated
     */
    public void setGetPtel(String getPtel) {
        this.getPtel = getPtel == null ? null : getPtel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.get_Addr
     *
     * @return the value of order1.get_Addr
     *
     * @mbg.generated
     */
    public String getGetAddr() {
        return getAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.get_Addr
     *
     * @param getAddr the value for order1.get_Addr
     *
     * @mbg.generated
     */
    public void setGetAddr(String getAddr) {
        this.getAddr = getAddr == null ? null : getAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.goods_Name
     *
     * @return the value of order1.goods_Name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.goods_Name
     *
     * @param goodsName the value for order1.goods_Name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.goods_Weight
     *
     * @return the value of order1.goods_Weight
     *
     * @mbg.generated
     */
    public Integer getGoodsWeight() {
        return goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.goods_Weight
     *
     * @param goodsWeight the value for order1.goods_Weight
     *
     * @mbg.generated
     */
    public void setGoodsWeight(Integer goodsWeight) {
        this.goodsWeight = goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.order_Type
     *
     * @return the value of order1.order_Type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.order_Type
     *
     * @param orderType the value for order1.order_Type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.order_State
     *
     * @return the value of order1.order_State
     *
     * @mbg.generated
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.order_State
     *
     * @param orderState the value for order1.order_State
     *
     * @mbg.generated
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState == null ? null : orderState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.order_PortPrice
     *
     * @return the value of order1.order_PortPrice
     *
     * @mbg.generated
     */
    public BigDecimal getOrderPortprice() {
        return orderPortprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.order_PortPrice
     *
     * @param orderPortprice the value for order1.order_PortPrice
     *
     * @mbg.generated
     */
    public void setOrderPortprice(BigDecimal orderPortprice) {
        this.orderPortprice = orderPortprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.transpor_Price
     *
     * @return the value of order1.transpor_Price
     *
     * @mbg.generated
     */
    public BigDecimal getTransporPrice() {
        return transporPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.transpor_Price
     *
     * @param transporPrice the value for order1.transpor_Price
     *
     * @mbg.generated
     */
    public void setTransporPrice(BigDecimal transporPrice) {
        this.transporPrice = transporPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.delivery_Price
     *
     * @return the value of order1.delivery_Price
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryPrice() {
        return deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.delivery_Price
     *
     * @param deliveryPrice the value for order1.delivery_Price
     *
     * @mbg.generated
     */
    public void setDeliveryPrice(BigDecimal deliveryPrice) {
        this.deliveryPrice = deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.total_price
     *
     * @return the value of order1.total_price
     *
     * @mbg.generated
     */
    public String getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.total_price
     *
     * @param totalPrice the value for order1.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice == null ? null : totalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order1.Comments
     *
     * @return the value of order1.Comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order1.Comments
     *
     * @param comments the value for order1.Comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}