package test.model;

public class Route {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.route_ID
     *
     * @mbg.generated
     */
    private String routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.city_ID
     *
     * @mbg.generated
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.province_ID
     *
     * @mbg.generated
     */
    private String provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.route_Name
     *
     * @mbg.generated
     */
    private String routeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.sart_province
     *
     * @mbg.generated
     */
    private String sartProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.start_City
     *
     * @mbg.generated
     */
    private String startCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.end_province
     *
     * @mbg.generated
     */
    private String endProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.end_city
     *
     * @mbg.generated
     */
    private String endCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.mid_province
     *
     * @mbg.generated
     */
    private String midProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.mid_City
     *
     * @mbg.generated
     */
    private String midCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.transpor_price
     *
     * @mbg.generated
     */
    private String transporPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.Comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.route_ID
     *
     * @return the value of route.route_ID
     *
     * @mbg.generated
     */
    public String getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.route_ID
     *
     * @param routeId the value for route.route_ID
     *
     * @mbg.generated
     */
    public void setRouteId(String routeId) {
        this.routeId = routeId == null ? null : routeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.city_ID
     *
     * @return the value of route.city_ID
     *
     * @mbg.generated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.city_ID
     *
     * @param cityId the value for route.city_ID
     *
     * @mbg.generated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.province_ID
     *
     * @return the value of route.province_ID
     *
     * @mbg.generated
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.province_ID
     *
     * @param provinceId the value for route.province_ID
     *
     * @mbg.generated
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.route_Name
     *
     * @return the value of route.route_Name
     *
     * @mbg.generated
     */
    public String getRouteName() {
        return routeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.route_Name
     *
     * @param routeName the value for route.route_Name
     *
     * @mbg.generated
     */
    public void setRouteName(String routeName) {
        this.routeName = routeName == null ? null : routeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.sart_province
     *
     * @return the value of route.sart_province
     *
     * @mbg.generated
     */
    public String getSartProvince() {
        return sartProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.sart_province
     *
     * @param sartProvince the value for route.sart_province
     *
     * @mbg.generated
     */
    public void setSartProvince(String sartProvince) {
        this.sartProvince = sartProvince == null ? null : sartProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.start_City
     *
     * @return the value of route.start_City
     *
     * @mbg.generated
     */
    public String getStartCity() {
        return startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.start_City
     *
     * @param startCity the value for route.start_City
     *
     * @mbg.generated
     */
    public void setStartCity(String startCity) {
        this.startCity = startCity == null ? null : startCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.end_province
     *
     * @return the value of route.end_province
     *
     * @mbg.generated
     */
    public String getEndProvince() {
        return endProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.end_province
     *
     * @param endProvince the value for route.end_province
     *
     * @mbg.generated
     */
    public void setEndProvince(String endProvince) {
        this.endProvince = endProvince == null ? null : endProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.end_city
     *
     * @return the value of route.end_city
     *
     * @mbg.generated
     */
    public String getEndCity() {
        return endCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.end_city
     *
     * @param endCity the value for route.end_city
     *
     * @mbg.generated
     */
    public void setEndCity(String endCity) {
        this.endCity = endCity == null ? null : endCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.mid_province
     *
     * @return the value of route.mid_province
     *
     * @mbg.generated
     */
    public String getMidProvince() {
        return midProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.mid_province
     *
     * @param midProvince the value for route.mid_province
     *
     * @mbg.generated
     */
    public void setMidProvince(String midProvince) {
        this.midProvince = midProvince == null ? null : midProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.mid_City
     *
     * @return the value of route.mid_City
     *
     * @mbg.generated
     */
    public String getMidCity() {
        return midCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.mid_City
     *
     * @param midCity the value for route.mid_City
     *
     * @mbg.generated
     */
    public void setMidCity(String midCity) {
        this.midCity = midCity == null ? null : midCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.transpor_price
     *
     * @return the value of route.transpor_price
     *
     * @mbg.generated
     */
    public String getTransporPrice() {
        return transporPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.transpor_price
     *
     * @param transporPrice the value for route.transpor_price
     *
     * @mbg.generated
     */
    public void setTransporPrice(String transporPrice) {
        this.transporPrice = transporPrice == null ? null : transporPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.Comments
     *
     * @return the value of route.Comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.Comments
     *
     * @param comments the value for route.Comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}